version: "3"
services:
    server:
        container_name: rabbitmq-server
        restart: always
        build: ./server
        ports:
            - '8000:8000'
        links: 
            - mongodb
            - rabbitmq
        depends_on: 
            - mongodb
            - rabbitmq
                  
    mongodb:
        container_name: mongodb
        image: mongo
        volumes: 
            - ./mongodb:/data/db
        ports: 
            - "27018:27017"
    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq"

    client:
        container_name: rabbitmq-client
        build: ./client
        restart: always
        ports: 
            - '3000:3000'
        depends_on: 
            - server
volumes:
    mongodb:

