version: "3"
services:
    server:
        container_name: rabbitmq-server
        restart: always
        build: server/
        ports:
            - '8000:8000'
        links: 
            - mongo
            - rabbitmq
        depends_on: 
            - mongo
            - rabbitmq
        environment:
            - MESSAGE_QUEUE=amqp://rabbitmq            
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27018:27017"
    rabbitmq:
        container_name: rabbitmq
        image: "rabbitmq"
        ports:
            - "5673:5672"
            - "15673:15672"
    client:
        container_name: rabbitmq-client
        build: client/
        restart: always
        network_mode: host
        ports: 
            - '3000:3000'
        depends_on: 
            - server
        environment:
            - MESSAGE_QUEUE=amqp://rabbitmq            
       