version: "3"
services:
    app:
        container_name: rabbitmq-server
        restart: always
        build: .
        ports:
            - '30:8000'
        links: 
            - mongo
            - rabbitmq
        depends_on: 
            - mongo
            - rabbitmq
    mongo:
        container_name: mongo
        image: mongo
        ports: 
            - "27018:27017"
    rabbitmq:
        image: "rabbitmq:management"
        ports:
            - "5673:5672"
            - "15673:15672"
